### ISSUE TITLE
Start some user-facing instructions for how to run the code

### ISSUE THREAD

**Issue by samcunliffe** [SainsburyWellcomeCentre/crabs-exploration#148]
## Definition of done

We have a nice README or similar doc pages explaining how to:

- [x] Run inference on a video for a given model.
- [x] Train a basic benchmark model (maybe not the full blow hyperparameter experiments)
- [x] Run training on the cluster guide
- [ ] Run training locally (see a starting point here https://github.com/SainsburyWellcomeCentre/crabs-exploration/pull/192)
- [x] Guide on how to use optuna
- [ ] Get the "final" evaluation metric out to compare to our models or for writing a paper (tracking metric?)

**Comment by sfmig** [comment]
Instructions to run the pipeline locally are now in the main README, including the evaluation metrics
