### ISSUE TITLE
Run inference on the cluster

### ISSUE THREAD

**Issue by sfmig** [SainsburyWellcomeCentre/crabs-exploration#186]
Streamline a bit the process of running inference on new videos using a trained model on the hpc.

Similar to #163 and the work done to run training on the cluster.

Including a quick guide if possible.

**Comment by samcunliffe** [comment]
Creating environment running into permissions errors...?

**Comment by samcunliffe** [comment]
[@sfmig to review the PR]

Inference:
- Producing tracks from a video.
- Can pass GT to inference to visualise GT vs tracking.
   - if you do this you might as well run the evaluation metrics(?)

What should we log? MLFlow?
- We don't always have a MOTA value.
- If we don't choose to save frames & don't have GT ... we should default to saving the CSV (but it's not necessarily log-able).

**Comment by samcunliffe** [comment]
Idea:

`crabs.tracking`
  - `crabs.tracking.inference`
  - `crabs.tracking.evaluation`

`crabs.detection`
 -  ❓ `crabs.detection.inference`
  - `crabs.detection.evaluation`

**Comment by sfmig** [comment]
Implemented in #251 with the new updates to the CLI and used to generate tracked videos.

It would need to be updated once MLflow is implemented for the detect-and-track command (see #254) - but we can close this issue now as that is now captured in #254
