### ISSUE TITLE
Try btrack.

### ISSUE THREAD

**Issue by samcunliffe** [SainsburyWellcomeCentre/crabs-exploration#41]
[quantumjot](https://github.com/quantumjot)/[btrack](https://github.com/quantumjot/btrack)

@paddyroddy can maybe help. Or at least we can complain to him.
[Here is an example with pollen under a microscope](https://github.com/quantumjot/btrack/discussions/221),

**Comment by sfmig** [comment]
btrack seems to perform well in situations in which the tracked object has relatively high contrast with the background, which is not our case. I tried [idtracker](https://idtracker.ai/latest/) which follows a somewhat similar approach, but didn't perform very well off-the-shelf, so closing this for now.
