### ISSUE TITLE
Add flake8 support for additional linting

### ISSUE THREAD

**Issue by nikk-nikaznan** [SainsburyWellcomeCentre/crabs-exploration#62]

**Comment by samcunliffe** [comment]
Looks like @sfmig grabbed the [pre-commit config](https://github.com/SainsburyWellcomeCentre/crabs-exploration/blob/main/.pre-commit-config.yaml) from the [NIU's python template](https://github.com/neuroinformatics-unit/python-cookiecutter) which is a good starting point (also `ruff` is much cooler than `flake8` 🕶️ ).

**Comment by samcunliffe** [comment]
What more linting/ci do we need?

I was wondering about [link-checker ci](https://github.com/UCL-ARC/python-tooling/blob/main/.github/workflows/links.yml) for the markdown documentation pages.

...and maybe there are more relevant [prebaked pre-commit hooks](https://github.com/pre-commit/pre-commit-hooks#hooks-available) for markdown docs and shell scripts.
