### ISSUE TITLE
Try VGG Image annotator "version" 3.

### ISSUE THREAD

**Issue by samcunliffe** [SainsburyWellcomeCentre/crabs-exploration#76]
Does version 3 suffer from [vgg/#340](https://gitlab.com/vgg/via/-/issues/340)? If not, can we use that instead?

**Comment by samcunliffe** [comment]
Hey @nikk-nikaznan ,
Sofia says you found this to be a no-goer? Is that right?

**Comment by nikk-nikaznan** [comment]
Yes, I played  around with the VGG annotator V3 but seems not working well for our basic image labelling. So me & Sofia think we just stick to v2 and do the post processing afterward. @sfmig [latest PR](https://github.com/SainsburyWellcomeCentre/crabs-exploration/pull/72) improved the post processing bit.
