### ISSUE TITLE
Refactor detection_tracking

### ISSUE THREAD

**Issue by nikk-nikaznan** [SainsburyWellcomeCentre/crabs-exploration#97]
- [x] `detection_utils` : is it better to split the utils to train and test
- [x]  `evaluate_model` : especially on `_load_dataset()` seems redundant to the one in training ( parent class that the evaluation class and the detector class inherit from)
- [x] refactor `inference_model.py` -- redundant of training end evaluate for some function
- [x] add EXPERIMENT_NAME to args
- [x] is there any other way to log lost function in mlflow without tensor board
- [x] check doc_string
- [x] [Pathlib instead of os.path](https://stackoverflow.com/questions/67112343/pathlib-vs-os-path-join-in-python/69619788#69619788)
- [x] replace print statements with calls to the logger (refer `evaluate.py`)
- [x] #95 
- [x] #96 
- [x] #91

**Comment by sfmig** [comment]
probably a good point to start : #108
